package fr.utt.lo02.jestgame.core;

public enum NotEvent {
	CREATE_PARTY_MENU,
	FACE_UP_MENU,
	FACE_UP_MENU_BOT,
	CATCH_UP_MENU,
	CATCH_UP_MENU_BOT,
	CATCH_UP_MENU_ERROR,
	CATCH_UP_MENU_SUCCESS,
	WIN_MENU,
	UPDATE_MENU,
	END_PARTY_MENU,
	CURRENT_PLAYER;

}
